src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Allow_Multiple_Product_With_Same_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this field is checked, the Contact can have more than one product from the same plan. Otherwise, Contact can only be able to select one per plan.</inlineHelpText>
        <label>Allow Multiple Product With Same Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Applied__c</fullName>
        <label>Discount Applied</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>Contact External ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Location</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Home_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plan_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Plan_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Plan Types</masterLabel>
</GlobalValueSet>

src/classes/Test_CTRL_ContactCase.cls
@IsTest
private class Test_CTRL_ContactCase {

    @TestSetup
    static void setup(){
        List<Product2> products = new List<Product2>{
            new Product2(
                Name = 'Product Test 1',
                ProductCode = 'Pro-Test 1',
                IsActive = true
            ),
            new Product2(
                Name = 'Product Test 2',
                ProductCode = 'Pro-Test 2',
                IsActive = true
            )
        };
        insert products;

        List<Country__c> countries = new List<Country__c>{
            new Country__c(Name = 'Germany'),
            new Country__c(Name = 'Spain')
        };
        insert countries;

        List<Contact> contacts = new List<Contact>{
            new Contact(
                LastName = 'Test 1',
                Product__c = products[0].Id,
                Home_Location__c =  countries[0].Id,
                ExternalID__c = '12345678',
                Allow_Multiple_Product_With_Same_Plan__c = true
            ),
            new Contact(
                LastName = 'Test 2',
                Product__c = products[1].Id,
                Home_Location__c =  countries[1].Id,
                ExternalID__c = '98765432',
                Discount_Applied__c = 5,
                Allow_Multiple_Product_With_Same_Plan__c = false
            )
        };
        insert contacts;

        List<Contact_Product__c> contactProducts = new List<Contact_Product__c>{
            new Contact_Product__c(
                Contact__c = contacts[0].Id,
                Product__c = products[0].Id,
                Plan_Type__c = 'Standard',
                Price__c = 10
            ),
            new Contact_Product__c(
                Contact__c = contacts[0].Id,
                Product__c = products[0].Id,
                Plan_Type__c = 'Metal',
                Price__c = 15
            ),
            new Contact_Product__c(
                Contact__c = contacts[1].Id,
                Product__c = products[1].Id,
                Plan_Type__c = 'Standard',
                Price__c = 20
            ),
            new Contact_Product__c(
                Contact__c = contacts[1].Id,
                Product__c = products[1].Id,
                Plan_Type__c = 'Metal',
                Price__c = 25
            )
        };
        insert contactProducts;
    }

    @IsTest
    static void testGetContactProductByContactId(){
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        System.assertEquals(2, CTRL_ContactCase.getContactProductByContactId(contact.Id).size());
    }

    @IsTest
    static void testUpsertContactProduct(){
        Contact contact = [SELECT Id, Name FROM Contact LIMIT 1];
        List<Contact_Product__c> contactProducts = [SELECT Id, Contact__c, Product__c FROM Contact_Product__c WHERE Contact__c =: contact.Id];
        for(Contact_Product__c contactProduct: contactProducts){
            contactProduct.Plan_Type__c = 'Metal';
        }
        contactProducts.add(new Contact_Product__c(
            Contact__c = contactProducts[0].Contact__c,
            Product__c = contactProducts[0].Product__c,
            Plan_Type__c = 'Metal',
            Price__c = 25)
        );
        CTRL_ContactCase.upsertContactProducts(contactProducts);
        System.assertEquals(contactProducts.size(), CTRL_ContactCase.getContactProductByContactId(contact.Id).size());
    }

    @IsTest
    static void testDeleteContactProduct(){
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        List<Contact_Product__c> contactProducts = [SELECT Id FROM Contact_Product__c WHERE Id =: contact.Id LIMIT 1];
        CTRL_ContactCase.deleteContactProducts(contactProducts);
        System.assertNotEquals(contactProducts.size(), CTRL_ContactCase.getContactProductByContactId(contact.Id).size());
    }
}