src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>Contact External ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Location</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Home_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plan_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Plan_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Plan Types</masterLabel>
</GlobalValueSet>

src/classes/ContactHTTPCallout.cls
@RestResource(UrlMapping='/ContactInformation/*')
global with sharing class ContactHTTPCallout {

    @HttpGet
    global static List<Contact> getContactInformation(){
        RestRequest req = RestContext.request;
        String contactExternalId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        List<Contact> contacts = [SELECT Id, Product__c, Home_Location__c, (SELECT Id, Plan_Type__c, Price__c FROM Contact_Products__r)
            FROM Contact WHERE ExternalID__c =: contactExternalId];
        return contacts;
    }
}