src/objects/Contact_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plan_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Plan_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Plan Types</masterLabel>
</GlobalValueSet>

src/classes/DAL_ContactProduct.cls
public with sharing class DAL_ContactProduct {

    public static List<Contact_Product__c> getContactProductByContactId(Id contactId){
        return [SELECT Id, Plan_Type__c, Price__c, Product__c, Discount__c FROM Contact_Product__c
            WHERE Contact__c =: contactId ORDER BY Plan_Type__c ASC];
    }

    public static List<AggregateResult> getContactProductByContactIdGroupByPlanType(Set<Id> contactsId){
        return [SELECT COUNT(Id) Records, Plan_Type__c, Contact__c FROM Contact_Product__c
            WHERE Contact__c =: contactsId GROUP BY Plan_Type__c, Contact__c];
    }

    public static List<Contact_Product__c> getContactProductsByContacts(Set<Id> idContacts){
        return [SELECT Id, Plan_Type__c, Price__c, Product__c, Discount__c, Contact__c FROM Contact_Product__c
            WHERE Contact__c IN: idContacts ORDER BY Plan_Type__c ASC];
    }
}