src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Allow_Multiple_Product_With_Same_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this field is checked, the Contact can have more than one product from the same plan. Otherwise, Contact can only be able to select one per plan.</inlineHelpText>
        <label>Allow Multiple Product With Same Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Applied__c</fullName>
        <label>Discount Applied</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Products</relationshipLabel>
        <relationshipName>Contact_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Plan_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contact Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Plan_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Plan Types</masterLabel>
</GlobalValueSet>

src/classes/TH_Contact.cls
public with sharing class TH_Contact{

    public static void checkIfTheContactHasMoreThanOneOfTheSamePlans(List<Contact> newList, Map<Id, Contact> oldMap){
        Set<Id> idContacts = new Set<Id>();
        for(Contact contact: newList){
            if(contact.Allow_Multiple_Product_With_Same_Plan__c != oldMap.get(contact.Id).Allow_Multiple_Product_With_Same_Plan__c
                    && !contact.Allow_Multiple_Product_With_Same_Plan__c){
                idContacts.add(contact.Id);
            }
        }
        if(!idContacts.isEmpty()){
            List<AggregateResult> contactProducts = DAL_ContactProduct.getContactProductByContactIdGroupByPlanType(idContacts);
            if(!contactProducts.isEmpty()){
                Map<Id, List<String>> mapContactProductTypesPerPerson = new Map<Id, List<String>>();
                for(AggregateResult aggregateResult: contactProducts){
                    if(Integer.valueOf(aggregateResult.get('Records')) > 1){
                        Id contactId = String.valueOf(aggregateResult.get('Contact__c'));
                        String contactProductPlanType = String.valueOf(aggregateResult.get('Plan_Type__c'));
                        if(mapContactProductTypesPerPerson.containsKey(contactId)){
                            mapContactProductTypesPerPerson.get(contactId).add(contactProductPlanType);
                        }else{
                            mapContactProductTypesPerPerson.put(contactId, new List<String>{contactProductPlanType});
                        }
                    }
                }
                if(!mapContactProductTypesPerPerson.isEmpty()){
                    for(Contact contact: newList){
                        if(mapContactProductTypesPerPerson.containsKey(contact.Id)){
                            String contactPlanTypes = String.join(mapContactProductTypesPerPerson.get(contact.Id), ', ');
                            contact.addError(Label.Contact_w_1_Product + ' ' + contactPlanTypes);
                        }
                    }
                }
            }
        }
    }

    public static void setIfDiscountAppliedChange(Map<Id, Contact> newMap, Map<Id, Contact> oldMap){
        Set<Id> idContacts = new Set<Id>();
        for(Contact contact: newMap.values()){
            if(contact.Discount_Applied__c != oldMap.get(contact.Id).Discount_Applied__c){
                idContacts.add(contact.Id);
            }
        }
        if(!idContacts.isEmpty()){
            List<Contact_Product__c> contactProducts = DAL_ContactProduct.getContactProductsByContacts(idContacts);
            for(Contact_Product__c contactProduct: contactProducts){
                Contact contact = newMap.containsKey(contactProduct.Contact__c)? newMap.get(contactProduct.Contact__c): null;
                contactProduct.Discount__c = contact.Discount_Applied__c;
                contactProduct.Price__c = (contact.Discount_Applied__c != null && contact.Discount_Applied__c != 0)?
                    contactProduct.Price__c - (contactProduct.Price__c * contact.Discount_Applied__c)/ 100: contactProduct.Price__c;
            }
            if(!contactProducts.isEmpty()){
                try{
                    update contactProducts;
                }catch(Exception e){
                    System.debug('Line number: ' + e.getLineNumber() +  ' - Cause: ' + e.getCause() + ' - Message: ' + e.getMessage());
                    throw e;
                }
            }
        }
    }
}